import { cn } from "@/lib/utils";

/**
 * The Rakshak mark, traced from `Logo/Logo.png`. `BrandMark` is the artwork
 * only; `BrandLockup` is artwork + wordmark. Both are served from
 * `/public/brand`, regenerated by `scripts/build_brand_assets.py`.
 *
 * Plain <img> (not next/image) because the assets are SVG and the project has
 * not enabled `images.dangerouslyAllowSVG`.
 */
export function BrandMark({ size = 32, className }: { size?: number; className?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/brand/rakshak-icon.svg"
      alt="NextGen Rakshak"
      width={size}
      height={size}
      className={cn("select-none", className)}
    />
  );
}

export function BrandLockup({ width = 168, className }: { width?: number; className?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/brand/rakshak-logo.svg"
      alt="NextGen Rakshak"
      width={width}
      height={Math.round((width * 160) / 560)}
      className={cn("select-none", className)}
    />
  );
}
